In [5]:
import numpy as np

In [6]:
#对角阵
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
#全零阵
a = np.zeros([2,3],dtype=float)
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#全一阵
a = np.ones([3,3],dtype = int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [12]:
a = np.arange(1,10,3,dtype=float)
a

array([1., 4., 7.])

In [13]:
#随机
a = np.random.rand(4,5)
a

array([[0.94605594, 0.04488552, 0.86181937, 0.55036636, 0.98955111],
       [0.14962905, 0.27840499, 0.41301708, 0.11062515, 0.68435586],
       [0.00683913, 0.88319367, 0.76656458, 0.89235715, 0.09104036],
       [0.30655838, 0.28268611, 0.03729042, 0.3588372 , 0.10839653]])

In [14]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#属性
a.shape#元组

(2, 3)

In [17]:
print("{}hang{}lie".format(a.shape[0],a.shape[1]))

2hang3lie


In [18]:
#总个数
a.size

6

In [ ]:
#reshape 不改变原来
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [20]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
#切片
a = np.arange(0,10,0.33)
a

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [22]:
a[0:8:2]

array([0.  , 0.66, 1.32, 1.98])

In [23]:
a = np.random.rand(5,5)
a

array([[0.39224404, 0.82291279, 0.98677423, 0.71920558, 0.87199083],
       [0.19485103, 0.08116257, 0.88868898, 0.74725347, 0.78452603],
       [0.49363729, 0.59429575, 0.73105154, 0.46203925, 0.73755528],
       [0.49702072, 0.84344937, 0.90043373, 0.38137213, 0.3128995 ],
       [0.37759779, 0.95854597, 0.57251822, 0.66099481, 0.48782701]])

In [24]:
#取出一列
a[:,2]

array([0.98677423, 0.88868898, 0.73105154, 0.90043373, 0.57251822])

In [25]:
a[3,:]

array([0.49702072, 0.84344937, 0.90043373, 0.38137213, 0.3128995 ])

In [26]:
#转置
a.T

array([[0.39224404, 0.19485103, 0.49363729, 0.49702072, 0.37759779],
       [0.82291279, 0.08116257, 0.59429575, 0.84344937, 0.95854597],
       [0.98677423, 0.88868898, 0.73105154, 0.90043373, 0.57251822],
       [0.71920558, 0.74725347, 0.46203925, 0.38137213, 0.66099481],
       [0.87199083, 0.78452603, 0.73755528, 0.3128995 , 0.48782701]])

In [31]:
#水平连接
#axis=0行
#axis=1列
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.hstack([a,b])
print(c)
c = np.concatenate([a,b],axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [32]:
#垂直
c = np.vstack([a,b])
print(c)
c = np.concatenate([a,b],axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#算术


In [34]:
#广播
a = np.arange(1,10).reshape(3,3)
b = np.array([[3]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a*b

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [36]:
b = np.array([[2,2,2]])
a*b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [37]:
#数学函数
np.random.seed(10)
a = (np.random.rand(5,6)-0.5)*10#(-5,5)
a

array([[ 2.71320643, -4.79248051,  1.33648235,  2.48803883, -0.01492988,
        -2.75203354],
       [-3.01937135,  2.60530712, -3.30889163, -4.11660186,  1.85359818,
         4.53393346],
       [-4.96051734,  0.12192263,  3.12620962,  1.12526067,  2.21755317,
        -2.08123932],
       [ 4.17774123,  2.14575783,  0.42544368, -3.57829952, -1.2665924 ,
         1.74133615],
       [-0.58166826, -0.65986007,  1.17766978,  0.13138243,  1.50397182,
         1.01038953]])

In [ ]:
#四舍五入保留两位
a_r = np.around(a,2)
a_r

array([[ 2.71, -4.79,  1.34,  2.49, -0.01, -2.75],
       [-3.02,  2.61, -3.31, -4.12,  1.85,  4.53],
       [-4.96,  0.12,  3.13,  1.13,  2.22, -2.08],
       [ 4.18,  2.15,  0.43, -3.58, -1.27,  1.74],
       [-0.58, -0.66,  1.18,  0.13,  1.5 ,  1.01]])

In [40]:
#向下取整
a_f= np.floor(a)
a_f

array([[ 2., -5.,  1.,  2., -1., -3.],
       [-4.,  2., -4., -5.,  1.,  4.],
       [-5.,  0.,  3.,  1.,  2., -3.],
       [ 4.,  2.,  0., -4., -2.,  1.],
       [-1., -1.,  1.,  0.,  1.,  1.]])

In [ ]:
#shang
a_c = np.ceil(a)
a_c

array([[ 3., -4.,  2.,  3., -0., -2.],
       [-3.,  3., -3., -4.,  2.,  5.],
       [-4.,  1.,  4.,  2.,  3., -2.],
       [ 5.,  3.,  1., -3., -1.,  2.],
       [-0., -0.,  2.,  1.,  2.,  2.]])

In [42]:
#幂函数
a = np.array([[1,2,3]])
np.power(a,2)

array([[1, 4, 9]])

In [ ]:
#e指数
np.exp(a)

array([[ 2.71828183,  7.3890561 , 20.08553692]])

In [ ]:
#exp2 log log2 log10

In [49]:
#统计函数
a = (np.random.rand(5,6)-0.5)*10#(-5,5)
a

array([[ 0.97371648,  4.0283176 ,  0.34557949,  0.90201363, -4.60718233,
        -1.42818241],
       [-4.2038691 , -1.94540082, -1.69280688,  2.73830296, -4.60040791,
        -0.70507822],
       [-1.85073128,  1.36491143, -1.5365285 , -4.56902644,  3.79915175,
         2.63240587],
       [ 3.78096643, -0.82490856,  1.05577564,  0.13466627,  0.97836648,
        -2.37784339],
       [-1.99128691, -4.74600218, -1.96937439, -2.57924125,  0.57578189,
         0.6550702 ]])

In [50]:
np.max(a)

np.float64(4.028317603316274)

In [51]:
np.min(a)

np.float64(-4.746002179498939)

In [52]:
np.ptp(a)

np.float64(8.774319782815212)

In [53]:
#列最大
np.max(a,axis=0)

array([3.78096643, 4.0283176 , 1.05577564, 2.73830296, 3.79915175,
       2.63240587])

In [54]:
#百分位数
np.percentile(a,[0,25,75,100])

array([-4.74600218, -1.98580878,  0.97720398,  4.0283176 ])

In [ ]:
#median mean std var

In [56]:
b = a[0,:]
b

array([ 0.97371648,  4.0283176 ,  0.34557949,  0.90201363, -4.60718233,
       -1.42818241])

In [58]:
b = np.sort(b)
b

array([-4.60718233, -1.42818241,  0.34557949,  0.90201363,  0.97371648,
        4.0283176 ])

In [61]:
c = b[::-1]
c

array([ 4.0283176 ,  0.97371648,  0.90201363,  0.34557949, -1.42818241,
       -4.60718233])

In [63]:
b = np.random.rand(1,10)
d = np.argsort(b)#索引
d

array([[2, 1, 8, 4, 7, 0, 5, 9, 6, 3]])